# Generated by Django 3.2.7 on 2021-10-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucessfull_transaction',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='unsucessfull_transaction',
            options={'ordering': ['-created_on']},
        ),
    ]
