# Generated by Django 3.2.7 on 2021-10-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('address', models.JSONField()),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('Phone_no', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.JSONField()),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('Phone_no', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(choices=[('BA', 'Business Analysts'), ('CSR', 'Customer Service Representative'), ('OC', 'Order Clerks'), ('DD', 'Delivery driver'), ('PM', 'Product Manager'), ('MM', 'Marketing manager')], default='PM', max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.company')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
