# Generated by Django 3.2.7 on 2021-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Business Analysts', 'Business Analysts'), ('Customer Service Representative', 'Customer Service Representative'), ('Order Clerks', 'Order Clerks'), ('Delivery driver', 'Delivery driver'), ('Product Manager', 'Product Manager'), ('Marketing manager', 'Marketing manager')], default='Marketing manager', max_length=50, null=True),
        ),
    ]
