# Generated by Django 3.2.7 on 2021-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('BA', 'Business Analysts'), ('CSR', 'Customer Service Representative'), ('OC', 'Order Clerks'), ('DD', 'Delivery driver'), ('PM', 'Product Manager'), ('MM', 'Marketing manager')], default='PM', max_length=20, null=True),
        ),
    ]
