# Generated by Django 3.2.7 on 2021-11-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
    ]
